# Generated by Django 2.1.8 on 2020-08-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0002_auto_20200806_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rdv',
            options={'verbose_name': 'Rendez-vou'},
        ),
        migrations.AddField(
            model_name='rdv',
            name='presence',
            field=models.BooleanField(default=True),
        ),
    ]
