# Generated by Django 2.1.8 on 2020-08-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0003_auto_20200806_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='presence',
            field=models.BooleanField(default=False),
        ),
    ]
