# Generated by Django 2.1.8 on 2020-08-06 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0004_auto_20200806_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdv',
            name='presence',
        ),
        migrations.AddField(
            model_name='rdv',
            name='status',
            field=models.CharField(choices=[('Absent', 'Absent'), ('Present', 'Present')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
