# Generated by Django 2.1.8 on 2020-08-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0005_auto_20200806_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rdv',
            old_name='nom_personnel',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='rdv',
            old_name='prenom_personnel',
            new_name='prenom',
        ),
        migrations.AlterField(
            model_name='rdv',
            name='status',
            field=models.CharField(choices=[('Absent', 'Absent'), ('Present', 'Present')], default='Absent', max_length=10),
        ),
    ]
