# Generated by Django 2.1.8 on 2020-08-08 15:10

from django.db import migrations, models
import rendez_vous.models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0006_auto_20200806_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='date',
            field=models.DateField(validators=[rendez_vous.models.Rdv.validate_date]),
        ),
    ]
