# Generated by Django 2.1.8 on 2020-08-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0008_siteweb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Siteweb',
        ),
        migrations.AddField(
            model_name='rdv',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
