# Generated by Django 2.1.8 on 2020-08-18 00:14

import datetime
from django.db import migrations, models
import rendez_vous.models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0010_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AlterModelOptions(
            name='rdv',
            options={'verbose_name': 'Rendez-vous', 'verbose_name_plural': 'Rendez-vous'},
        ),
        migrations.AlterField(
            model_name='rdv',
            name='date',
            field=models.DateField(default=datetime.date.today, validators=[rendez_vous.models.Rdv.validate_date]),
        ),
        migrations.AlterField(
            model_name='rdv',
            name='heure',
            field=models.TimeField(),
        ),
        migrations.DeleteModel(
            name='Heure',
        ),
    ]
