# Generated by Django 2.1.8 on 2020-08-05 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='specialiteF',
            new_name='specialisteF',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='specialiteM',
            new_name='specialisteM',
        ),
    ]
