# Generated by Django 2.1.8 on 2020-08-06 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_titre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='image',
            new_name='image_service',
        ),
        migrations.RemoveField(
            model_name='service',
            name='id',
        ),
        migrations.RemoveField(
            model_name='titre',
            name='id',
        ),
        migrations.AlterField(
            model_name='service',
            name='nom_service',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='specialisteF',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='specialisteM',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='titre',
            name='titre',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
