# Generated by Django 2.1.8 on 2020-08-06 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_personnel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnel',
            old_name='nom',
            new_name='nom_personnel',
        ),
        migrations.RenameField(
            model_name='personnel',
            old_name='prenom',
            new_name='prenom_personnel',
        ),
        migrations.AlterField(
            model_name='personnel',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Service'),
        ),
    ]
