# Generated by Django 2.1.8 on 2020-08-09 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_auto_20200809_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='photo_personnel',
            field=models.ImageField(default='imgdefaut.jpeg', upload_to='imgdefaut/'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Service'),
        ),
    ]
