# Generated by Django 2.1.8 on 2020-08-18 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0022_auto_20200818_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='tweeter',
        ),
        migrations.AddField(
            model_name='personnel',
            name='twitter',
            field=models.URLField(blank=True, default='#'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='email',
            field=models.EmailField(blank=True, default='#', max_length=254),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='facebook',
            field=models.URLField(blank=True, default='#'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='instagram',
            field=models.URLField(blank=True, default='#'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Service'),
        ),
    ]
