# Generated by Django 2.1.8 on 2020-08-18 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_auto_20200818_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='twitter',
        ),
        migrations.AlterField(
            model_name='personnel',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Service'),
        ),
    ]
